stages:
  - validate
  - test
  - publish

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

.rust-base:
  image: rust:1
  cache:
    - key:
        files:
          - Cargo.lock
      paths:
        - .cargo/
        - target/
      fallback_keys:
        - rust-fallback

include:
  - .gitlab/ci/lint.yml
  - .gitlab/ci/test.yml
  - .gitlab/ci/security.yml
  - .gitlab/ci/documentation.yml
  - .gitlab/ci/build.yml
