[package]
name = "PaaSTech"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "uuid", "chrono", "json"] }
serde_json = "1"
uuid = { version = "1", features = ["serde", "v4"] }
actix-web = "4"
actix-multipart = "0.7"
futures-util = "0.3"
tokio = "1.52.1"
bollard = "*"
dotenvy = "0.15"
serde = { version = "1.0.228", features = ["derive"] }
chrono = { version = "0.4.44", features = ["serde"] }
zip-extract = "0.2.1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
