
build:
  extends: .rust-base
  stage: build
  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - .cargo/registry/
        - .cargo/git/
        - .cargo/bin/
      policy: pull-push
    - key: "target-$CI_PIPELINE_ID"
      paths:
        - target/
      policy: push
  script:
    - cargo install cargo-nextest cargo-audit --locked
    - cargo nextest run --no-run --profile ci
