
build:
  extends: .rust-base
  stage: build
  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - .cargo/registry/
        - .cargo/git/
        - .cargo/bin/
      policy: pull-push
    - key: "target-$CI_PIPELINE_ID"
      paths:
        - target/
      policy: push
  script:
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - cargo binstall cargo-nextest cargo-audit --no-confirm
    - cargo nextest run --no-run --profile ci
